### PR TITLE
added simple css 🔍

### PR DESCRIPTION
**Pull request by gkmzfk6um**
Bildschirmfoto am 2023-02-28 um 23 48 17

[NEW]Favico 
favico

### CODE REVIEW

**Comment by SolarWolf-Code** [comment]
@gkmzfk6um may want to include the [rust png](https://rustacean.net/assets/rustacean-orig-noshadow.png) inside PR. After all the end goal of the project is to be able to not need internet :))

**Comment by gkmzfk6um** [comment]
> @gkmzfk6um may want to include the [rust png](https://rustacean.net/assets/rustacean-orig-noshadow.png) inside PR. After all the end goal of the project is to be able to not need internet :))

Yeah you're right. I was lazy

**Comment by wowkster** [comment]
I'm a big fan of these changes, is there any reason is hasn't been merged?

**Comment by RealPacket** [comment]
add dark mode

**Comment by RealPacket** [comment]
Why?

**Comment by gkmzfk6um** [comment]
> Why?
i dont understand ether what happend?

**Comment by gkmzfk6um** [comment]
> Why?

i dont understand what happend?

**Pull request closed without merging**
